# Generated by Django 5.0.4 on 2024-08-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.CharField(choices=[('0.11', '11%'), ('0.24', '24%')], default=0),
        ),
    ]
